import type { Metadata } from "next";
import {Open_Sans} from 'next/font/google';
import "./globals.css";

import {
  ClerkProvider
} from '@clerk/nextjs'

const sans=Open_Sans({subsets:['latin']})

export const metadata: Metadata = {
  title: "Buisness Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
     <html lang="en">
      <body
        className={`${sans.className}`}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
